version: "3"
services:
    ghost:
        image: ghost:alpine
        restart: always
        ports:
            - 8080:2368
        depends_on:
            - db
        environment:
            database__client: mysql
            database__connection__host: db
            database__connection__user: root
            database__connection__password: changeme
            database__connection__database: ghost

    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: changeme
